-- Tally shared-team schema (Supabase / Postgres).
--
-- This mirrors the local SQLite schema in src/main/db.ts, with one addition:
-- every row that belongs to a human carries a `person_id`, so the whole team's
-- time can live in one database without colliding. Each machine keeps its own
-- local SQLite store (so tracking still works offline); this is the shared
-- copy that team-wide views read from.
--
-- Apply with:  psql "$DATABASE_URL" -f supabase/schema.sql
-- (or paste into the Supabase SQL editor).
--
-- Deliberately NOT mirrored from the local schema:
--   * report_history  — stores local Windows PDF/CSV paths; meaningless on
--                       another machine.
--   * app_settings    — machine-local prefs (shortcuts, auto-launch).

-- Team members. One row per person, not per machine.
CREATE TABLE IF NOT EXISTS people (
  id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name   TEXT NOT NULL UNIQUE,
  active BOOLEAN NOT NULL DEFAULT true
);

-- Clients are CANONICAL here and shared by the whole team: ids must mean the
-- same thing on every machine, which is why the shared copy is the source of
-- truth rather than each machine's local autoincrement.
CREATE TABLE IF NOT EXISTS clients (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          TEXT NOT NULL UNIQUE,
  billable_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
  color         TEXT NOT NULL DEFAULT '#6366f1'
);

CREATE TABLE IF NOT EXISTS rules (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_app         TEXT,
  match_title_regex TEXT,
  match_domain      TEXT,
  client_id         INTEGER REFERENCES clients(id) ON DELETE CASCADE,
  billable          BOOLEAN NOT NULL DEFAULT true,
  priority          INTEGER NOT NULL DEFAULT 100
);

-- Per-day rollup of tracked activity, per person.
--
-- NOTE ON client_id: locally this column is nullable ("time not attributed to
-- any client" — the majority of rows, since only manual-timer windows
-- attribute). Postgres forbids NULL in a primary key, so the shared copy uses
-- -1 as the "no client" sentinel. Anything reading this table must map -1 back
-- to null. person_id leads the key so two people's identical day never collide.
CREATE TABLE IF NOT EXISTS daily_activity (
  person_id  INTEGER NOT NULL REFERENCES people(id) ON DELETE CASCADE,
  day        TEXT NOT NULL,
  client_id  INTEGER NOT NULL DEFAULT -1,   -- -1 = no client (local NULL)
  app        TEXT NOT NULL,
  activity   TEXT NOT NULL,
  host       TEXT NOT NULL DEFAULT '',
  billable   BOOLEAN NOT NULL DEFAULT false,
  seconds    INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (person_id, day, client_id, app, activity, host)
);

-- A manual timer window: the heart of attribution (see main's analytics.ts —
-- everything inside the window belongs to the session's client).
CREATE TABLE IF NOT EXISTS timer_sessions (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  person_id  INTEGER NOT NULL REFERENCES people(id) ON DELETE CASCADE,
  client_id  INTEGER NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  start_time TEXT NOT NULL,
  end_time   TEXT,
  notes      TEXT,
  created_at TEXT NOT NULL DEFAULT (now()::text)
);

CREATE TABLE IF NOT EXISTS session_exclusions (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id INTEGER NOT NULL REFERENCES timer_sessions(id) ON DELETE CASCADE,
  app        TEXT NOT NULL,
  host       TEXT NOT NULL,
  activity   TEXT NOT NULL
);

-- Immutable record of what a session actually contained, captured when the
-- timer stops. Client-facing proof of work: must not drift if ActivityWatch's
-- live data changes shape afterwards.
CREATE TABLE IF NOT EXISTS session_activity_snapshot (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id INTEGER NOT NULL REFERENCES timer_sessions(id) ON DELETE CASCADE,
  app        TEXT NOT NULL,
  host       TEXT NOT NULL,
  activity   TEXT NOT NULL,
  seconds    INTEGER NOT NULL DEFAULT 0
);

-- Days whose rollup is complete, per person.
CREATE TABLE IF NOT EXISTS day_finalized (
  person_id INTEGER NOT NULL REFERENCES people(id) ON DELETE CASCADE,
  day       TEXT NOT NULL,
  PRIMARY KEY (person_id, day)
);

CREATE INDEX IF NOT EXISTS idx_sessions_person_start ON timer_sessions(person_id, start_time);
CREATE INDEX IF NOT EXISTS idx_exclusions_session ON session_exclusions(session_id);
CREATE INDEX IF NOT EXISTS idx_snapshot_session ON session_activity_snapshot(session_id);
CREATE INDEX IF NOT EXISTS idx_activity_day ON daily_activity(day);
