// Persistence for the shared team instance — Supabase/Postgres, shared by
// every deployed instance and every developer's local `npm run dev`.
//
// Stores the things ActivityWatch doesn't know about: the team members
// (`people`), the firm's clients and billable rates, and the mapping rules that
// attribute usage to them. It keeps a per-person per-day *rollup* of categorized
// usage (`daily_activity`) plus the raw pushed events (`pushed_events`) that are
// the source for re-categorization. Raw events originate on each machine's
// ActivityWatch and are pushed in via lib/ingest.
//
// Schema lives in lib/schema.sql (the same CREATE TABLE IF NOT EXISTS
// statements run here on first connect, so a fresh Supabase project needs no
// manual step beyond setting DATABASE_URL).

import postgres from "postgres";
import crypto from "node:crypto";
import type { Client, MappingRule, Person, RuleMatch } from "./types";

function connectionString(): string {
  const url = process.env.DATABASE_URL || process.env.SUPABASE_DB_URL;
  if (!url) {
    throw new Error(
      "DATABASE_URL is not set — point it at your Supabase Postgres connection string " +
        "(Project Settings -> Database -> Connection string).",
    );
  }
  return url;
}

let _sql: postgres.Sql | null = null;
let _ready: Promise<void> | null = null;

/** The shared postgres.js client, lazily created and migrated exactly once. */
async function db(): Promise<postgres.Sql> {
  if (!_sql) {
    _sql = postgres(connectionString(), {
      // Supabase's pooled connection string already terminates TLS; `require`
      // works for both the direct and pooler (pgbouncer) connection strings.
      ssl: "require",
    });
  }
  if (!_ready) {
    _ready = (async () => {
      await migrate(_sql!);
      await seedDefaultPerson(_sql!);
      await seedIfEmpty(_sql!);
    })();
  }
  await _ready;
  return _sql;
}

async function migrate(sql: postgres.Sql): Promise<void> {
  await sql.unsafe(`
    CREATE TABLE IF NOT EXISTS people (
      id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name   TEXT NOT NULL,
      token  TEXT NOT NULL UNIQUE,
      active BOOLEAN NOT NULL DEFAULT true
    );
    CREATE TABLE IF NOT EXISTS clients (
      id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name                TEXT NOT NULL UNIQUE,
      billable_rate       DOUBLE PRECISION NOT NULL DEFAULT 0,
      color               TEXT,
      chrome_profile_dir  TEXT,
      chrome_profile_name TEXT
    );
    CREATE TABLE IF NOT EXISTS rules (
      id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      match_app     TEXT,
      match_title   TEXT,
      match_domain  TEXT,
      match_profile TEXT,
      client_id     INTEGER REFERENCES clients(id) ON DELETE SET NULL,
      project       TEXT,
      billable      BOOLEAN NOT NULL DEFAULT true,
      priority      INTEGER NOT NULL DEFAULT 100
    );
    CREATE TABLE IF NOT EXISTS daily_activity (
      person_id  INTEGER NOT NULL DEFAULT 1,
      day        TEXT NOT NULL,
      client_id  INTEGER NOT NULL,
      app        TEXT NOT NULL,
      activity   TEXT NOT NULL,
      host       TEXT NOT NULL DEFAULT '',
      profile    TEXT NOT NULL DEFAULT '',
      billable   BOOLEAN NOT NULL DEFAULT false,
      unassigned BOOLEAN NOT NULL DEFAULT false,
      seconds    INTEGER NOT NULL DEFAULT 0,
      PRIMARY KEY (person_id, day, client_id, app, activity, host, profile, billable, unassigned)
    );
    CREATE TABLE IF NOT EXISTS pushed_events (
      person_id   INTEGER NOT NULL,
      day         TEXT NOT NULL,
      events_json JSONB NOT NULL,
      received_at TEXT NOT NULL,
      PRIMARY KEY (person_id, day)
    );
    CREATE TABLE IF NOT EXISTS day_finalized (
      day          TEXT PRIMARY KEY,
      finalized_at TEXT NOT NULL
    );
    CREATE TABLE IF NOT EXISTS cleanup_cache (
      raw                   TEXT PRIMARY KEY,
      kind                  TEXT NOT NULL,
      cleaned_label         TEXT NOT NULL,
      is_per_client         BOOLEAN NOT NULL DEFAULT false,
      suggested_domain      TEXT,
      suggested_client_name TEXT,
      confidence            DOUBLE PRECISION NOT NULL DEFAULT 0,
      model                 TEXT NOT NULL,
      updated_at            TEXT NOT NULL
    );
    CREATE TABLE IF NOT EXISTS app_settings (
      key   TEXT PRIMARY KEY,
      value TEXT
    );
  `);
}

/** The -1 sentinel used in daily_activity for "no client". */
const NO_CLIENT = -1;

export interface DailyActivityRow {
  personId: number;
  day: string;
  clientId: number | null;
  app: string;
  activity: string;
  host: string;
  profile: string;
  billable: boolean;
  unassigned: boolean;
  seconds: number;
}

interface DailyActivityDbRow {
  person_id: number;
  day: string;
  client_id: number;
  app: string;
  activity: string;
  host: string;
  profile: string;
  billable: boolean;
  unassigned: boolean;
  seconds: number;
}

function toDailyRow(r: DailyActivityDbRow): DailyActivityRow {
  return {
    personId: r.person_id,
    day: r.day,
    clientId: r.client_id === NO_CLIENT ? null : r.client_id,
    app: r.app,
    activity: r.activity,
    host: r.host,
    profile: r.profile,
    billable: !!r.billable,
    unassigned: !!r.unassigned,
    seconds: r.seconds,
  };
}

/**
 * Replace one person's rollup for a single day atomically. The DELETE is scoped
 * to (person_id, day) — NOT day alone — so a teammate's sync never wipes the
 * rest of the team's rows for that day.
 */
export async function replaceDayActivity(
  personId: number,
  day: string,
  rows: DailyActivityRow[],
): Promise<void> {
  const sql = await db();
  await sql.begin(async (tx) => {
    await tx`DELETE FROM daily_activity WHERE person_id = ${personId} AND day = ${day}`;
    for (const r of rows) {
      await tx`
        INSERT INTO daily_activity
          (person_id, day, client_id, app, activity, host, profile, billable, unassigned, seconds)
        VALUES (${personId}, ${day}, ${r.clientId ?? NO_CLIENT}, ${r.app}, ${r.activity},
                ${r.host}, ${r.profile}, ${r.billable}, ${r.unassigned}, ${Math.round(r.seconds)})
      `;
    }
  });
}

/**
 * Fetch stored rollup rows for an inclusive day range [startDay, endDay].
 * Omit `personId` for the whole team (the recap view); pass it to scope to one
 * person.
 */
export async function getActivityRows(
  startDay: string,
  endDay: string,
  personId?: number,
): Promise<DailyActivityRow[]> {
  const sql = await db();
  const rows =
    personId === undefined
      ? await sql<DailyActivityDbRow[]>`
          SELECT * FROM daily_activity WHERE day >= ${startDay} AND day <= ${endDay} ORDER BY day
        `
      : await sql<DailyActivityDbRow[]>`
          SELECT * FROM daily_activity
          WHERE person_id = ${personId} AND day >= ${startDay} AND day <= ${endDay}
          ORDER BY day
        `;
  return rows.map(toDailyRow);
}

export async function markFinalized(day: string, finalizedAt: string): Promise<void> {
  const sql = await db();
  await sql`
    INSERT INTO day_finalized (day, finalized_at) VALUES (${day}, ${finalizedAt})
    ON CONFLICT (day) DO UPDATE SET finalized_at = excluded.finalized_at
  `;
}

export async function isFinalized(day: string): Promise<boolean> {
  const sql = await db();
  const rows = await sql`SELECT 1 FROM day_finalized WHERE day = ${day}`;
  return rows.length > 0;
}

export async function clearDayFinalized(day: string): Promise<void> {
  const sql = await db();
  await sql`DELETE FROM day_finalized WHERE day = ${day}`;
}

// ---- cleanup cache (LLM enrichment) --------------------------------------

export interface CleanupRow {
  raw: string;
  kind: "site" | "title";
  cleanedLabel: string;
  isPerClient: boolean;
  suggestedDomain: string | null;
  suggestedClientName: string | null;
  confidence: number;
  model: string;
}

interface CleanupDbRow {
  raw: string;
  kind: string;
  cleaned_label: string;
  is_per_client: boolean;
  suggested_domain: string | null;
  suggested_client_name: string | null;
  confidence: number;
  model: string;
}

function toCleanupRow(r: CleanupDbRow): CleanupRow {
  return {
    raw: r.raw,
    kind: r.kind === "title" ? "title" : "site",
    cleanedLabel: r.cleaned_label,
    isPerClient: !!r.is_per_client,
    suggestedDomain: r.suggested_domain,
    suggestedClientName: r.suggested_client_name,
    confidence: r.confidence,
    model: r.model,
  };
}

/** All cached cleanups for the given model, keyed by raw host/title. */
export async function getCleanupCache(model: string): Promise<Map<string, CleanupRow>> {
  const sql = await db();
  const rows = (await sql<CleanupDbRow[]>`
    SELECT * FROM cleanup_cache WHERE model = ${model}
  `).map(toCleanupRow);
  return new Map(rows.map((r) => [r.raw, r]));
}

/** Cached cleanups for a specific set of raw keys (for diffing before a run). */
export async function getCleanupFor(
  raws: string[],
  model: string,
): Promise<Map<string, CleanupRow>> {
  if (raws.length === 0) return new Map();
  const sql = await db();
  const rows = await sql<CleanupDbRow[]>`
    SELECT * FROM cleanup_cache WHERE model = ${model} AND raw IN ${sql(raws)}
  `;
  return new Map(rows.map((r) => [r.raw, toCleanupRow(r)]));
}

/** Insert or overwrite cleanup rows (re-cleaning replaces prior values). */
export async function upsertCleanup(rows: CleanupRow[], updatedAt: string): Promise<void> {
  const sql = await db();
  await sql.begin(async (tx) => {
    for (const r of rows) {
      await tx`
        INSERT INTO cleanup_cache
          (raw, kind, cleaned_label, is_per_client, suggested_domain,
           suggested_client_name, confidence, model, updated_at)
        VALUES (${r.raw}, ${r.kind}, ${r.cleanedLabel}, ${r.isPerClient}, ${r.suggestedDomain},
                ${r.suggestedClientName}, ${r.confidence}, ${r.model}, ${updatedAt})
        ON CONFLICT (raw) DO UPDATE SET
          kind = excluded.kind,
          cleaned_label = excluded.cleaned_label,
          is_per_client = excluded.is_per_client,
          suggested_domain = excluded.suggested_domain,
          suggested_client_name = excluded.suggested_client_name,
          confidence = excluded.confidence,
          model = excluded.model,
          updated_at = excluded.updated_at
      `;
    }
  });
}

export async function clearCleanupCache(): Promise<void> {
  const sql = await db();
  await sql`DELETE FROM cleanup_cache`;
}

// ---- app settings (key/value) --------------------------------------------

export async function getSetting(key: string): Promise<string | null> {
  const sql = await db();
  const rows = await sql<{ value: string | null }[]>`
    SELECT value FROM app_settings WHERE key = ${key}
  `;
  return rows.length > 0 ? rows[0].value : null;
}

export async function setSetting(key: string, value: string | null): Promise<void> {
  const sql = await db();
  await sql`
    INSERT INTO app_settings (key, value) VALUES (${key}, ${value})
    ON CONFLICT (key) DO UPDATE SET value = excluded.value
  `;
}

// ---- people --------------------------------------------------------------

interface PersonRow {
  id: number;
  name: string;
  token: string;
  active: boolean;
}

function toPerson(r: PersonRow): Person {
  return { id: r.id, name: r.name, active: !!r.active };
}

/** Generate an opaque bearer token for a person's push agent. */
export function newPersonToken(): string {
  return crypto.randomBytes(24).toString("base64url");
}

/** All people (token omitted — never returned to the UI). */
export async function listPeople(): Promise<Person[]> {
  const sql = await db();
  const rows = await sql<PersonRow[]>`SELECT * FROM people ORDER BY name`;
  return rows.map(toPerson);
}

export async function getPerson(id: number): Promise<Person | undefined> {
  const sql = await db();
  const rows = await sql<PersonRow[]>`SELECT * FROM people WHERE id = ${id}`;
  return rows.length > 0 ? toPerson(rows[0]) : undefined;
}

/** Resolve a person from the bearer token an agent presents (active only). */
export async function getPersonByToken(token: string): Promise<Person | undefined> {
  if (!token) return undefined;
  const sql = await db();
  const rows = await sql<PersonRow[]>`
    SELECT * FROM people WHERE token = ${token} AND active = true
  `;
  return rows.length > 0 ? toPerson(rows[0]) : undefined;
}

/** Create a person, returning the row plus the freshly-issued token (shown once). */
export async function createPerson(
  name: string,
  token: string = newPersonToken(),
): Promise<{ person: Person; token: string }> {
  const sql = await db();
  const rows = await sql<PersonRow[]>`
    INSERT INTO people (name, token) VALUES (${name}, ${token}) RETURNING *
  `;
  return { person: toPerson(rows[0]), token };
}

export async function deletePerson(id: number): Promise<void> {
  const sql = await db();
  await sql`DELETE FROM people WHERE id = ${id}`;
}

// ---- pushed events (central "source" for re-categorization) ---------------

export interface PushedDay {
  personId: number;
  day: string;
}

/** Store (replace) one person's raw pushed events for a day. */
export async function storePushedEvents(
  personId: number,
  day: string,
  eventsJson: string,
  receivedAt: string,
): Promise<void> {
  const sql = await db();
  await sql`
    INSERT INTO pushed_events (person_id, day, events_json, received_at)
    VALUES (${personId}, ${day}, ${eventsJson}, ${receivedAt})
    ON CONFLICT (person_id, day) DO UPDATE SET
      events_json = excluded.events_json,
      received_at = excluded.received_at
  `;
}

/** Read one person-day's raw pushed events JSON (undefined if none stored). */
export async function getPushedEvents(
  personId: number,
  day: string,
): Promise<string | undefined> {
  const sql = await db();
  const rows = await sql<{ events_json: unknown }[]>`
    SELECT events_json FROM pushed_events WHERE person_id = ${personId} AND day = ${day}
  `;
  if (rows.length === 0) return undefined;
  const raw = rows[0].events_json;
  // jsonb comes back already parsed from postgres.js; downstream code
  // (lib/ingest.ts) does JSON.parse on this, so re-stringify for compatibility.
  return typeof raw === "string" ? raw : JSON.stringify(raw);
}

/** All (person, day) pairs with stored events in [startDay, endDay] — drives re-sync. */
export async function listPushedDays(
  startDay: string,
  endDay: string,
): Promise<PushedDay[]> {
  const sql = await db();
  const rows = await sql<{ person_id: number; day: string }[]>`
    SELECT person_id, day FROM pushed_events
    WHERE day >= ${startDay} AND day <= ${endDay}
    ORDER BY person_id, day
  `;
  return rows.map((r) => ({ personId: r.person_id, day: r.day }));
}

// ---- row mapping ---------------------------------------------------------

interface ClientRow {
  id: number;
  name: string;
  billable_rate: number;
  color: string | null;
  chrome_profile_dir: string | null;
  chrome_profile_name: string | null;
}
interface RuleRow {
  id: number;
  match_app: string | null;
  match_title: string | null;
  match_domain: string | null;
  match_profile: string | null;
  client_id: number | null;
  project: string | null;
  billable: boolean;
  priority: number;
}

function toClient(r: ClientRow): Client {
  return {
    id: r.id,
    name: r.name,
    billableRate: r.billable_rate,
    color: r.color ?? undefined,
    chromeProfileDir: r.chrome_profile_dir ?? undefined,
    chromeProfileName: r.chrome_profile_name ?? undefined,
  };
}

function toRule(r: RuleRow): MappingRule {
  const match: RuleMatch = {};
  if (r.match_app) match.app = r.match_app;
  if (r.match_title) match.titleRegex = r.match_title;
  if (r.match_domain) match.urlDomain = r.match_domain;
  if (r.match_profile) match.profile = r.match_profile;
  return {
    id: r.id,
    match,
    clientId: r.client_id,
    project: r.project,
    billable: !!r.billable,
    priority: r.priority,
  };
}

// ---- clients -------------------------------------------------------------

export async function listClients(): Promise<Client[]> {
  const sql = await db();
  const rows = await sql<ClientRow[]>`SELECT * FROM clients ORDER BY name`;
  return rows.map(toClient);
}

export async function createClient(
  name: string,
  billableRate: number,
  color?: string,
): Promise<Client> {
  const sql = await db();
  const rows = await sql<ClientRow[]>`
    INSERT INTO clients (name, billable_rate, color)
    VALUES (${name}, ${billableRate}, ${color ?? null})
    RETURNING *
  `;
  return toClient(rows[0]);
}

export async function getClient(id: number): Promise<Client | undefined> {
  const sql = await db();
  const rows = await sql<ClientRow[]>`SELECT * FROM clients WHERE id = ${id}`;
  return rows.length > 0 ? toClient(rows[0]) : undefined;
}

export async function updateClient(
  id: number,
  fields: Partial<Pick<Client, "name" | "billableRate" | "color">>,
): Promise<Client | undefined> {
  const existing = await getClient(id);
  if (!existing) return undefined;
  const next = { ...existing, ...fields };
  const sql = await db();
  await sql`
    UPDATE clients SET name = ${next.name}, billable_rate = ${next.billableRate}, color = ${next.color ?? null}
    WHERE id = ${id}
  `;
  return getClient(id);
}

export async function deleteClient(id: number): Promise<void> {
  const sql = await db();
  await sql`DELETE FROM clients WHERE id = ${id}`;
}

/** Record the Chrome profile (directory + display name) Tally provisioned for a client. */
export async function setClientChromeProfile(
  id: number,
  dir: string,
  name: string,
): Promise<Client | undefined> {
  const sql = await db();
  await sql`
    UPDATE clients SET chrome_profile_dir = ${dir}, chrome_profile_name = ${name}
    WHERE id = ${id}
  `;
  return getClient(id);
}

// ---- rules ---------------------------------------------------------------

export async function listRules(): Promise<MappingRule[]> {
  const sql = await db();
  const rows = await sql<RuleRow[]>`SELECT * FROM rules ORDER BY priority, id`;
  return rows.map(toRule);
}

export interface RuleInput {
  match: RuleMatch;
  clientId: number | null;
  project?: string | null;
  billable?: boolean;
  priority?: number;
}

export async function createRule(input: RuleInput): Promise<MappingRule> {
  const sql = await db();
  const rows = await sql<RuleRow[]>`
    INSERT INTO rules (match_app, match_title, match_domain, match_profile, client_id, project, billable, priority)
    VALUES (${input.match.app ?? null}, ${input.match.titleRegex ?? null}, ${input.match.urlDomain ?? null},
            ${input.match.profile ?? null}, ${input.clientId}, ${input.project ?? null},
            ${input.billable === false ? false : true}, ${input.priority ?? 100})
    RETURNING *
  `;
  return toRule(rows[0]);
}

export async function deleteRule(id: number): Promise<void> {
  const sql = await db();
  await sql`DELETE FROM rules WHERE id = ${id}`;
}

// ---- seed ----------------------------------------------------------------

/**
 * Ensure at least one person (id 1) exists, so single-user local dev works with
 * no admin step. On a shared instance the admin adds the real teammates; this
 * just guarantees the default is present. A dev machine can pin the default
 * person's token via TALLY_PERSON_TOKEN so its agent can push to a freshly-
 * seeded database.
 */
async function seedDefaultPerson(sql: postgres.Sql): Promise<void> {
  const [{ n }] = await sql<{ n: number }[]>`SELECT COUNT(*)::int AS n FROM people`;
  if (n > 0) return;
  const name = process.env.TALLY_PERSON_NAME || "Me";
  const token = process.env.TALLY_PERSON_TOKEN || newPersonToken();
  await sql`INSERT INTO people (name, token) VALUES (${name}, ${token})`;
}

/**
 * On first run, seed the apps the firm uses so the dashboard shows meaningful
 * structure immediately. Client-specific PM-tool domains are added by the user
 * (or via suggested rules) since they vary per engagement.
 *
 * "Internal / Admin" (id assigned at seed time) collects firm-internal,
 * non-billable time like Teams and Outlook unless a more specific client rule
 * matches first (lower priority number).
 */
async function seedIfEmpty(sql: postgres.Sql): Promise<void> {
  const [{ n }] = await sql<{ n: number }[]>`SELECT COUNT(*)::int AS n FROM clients`;
  if (n > 0) return;

  const [internal] = await sql<{ id: number }[]>`
    INSERT INTO clients (name, billable_rate, color) VALUES ('Internal / Admin', 0, 'gray') RETURNING id
  `;
  const internalId = internal.id;
  // A couple of example billable clients so charts aren't empty pre-config.
  await sql`INSERT INTO clients (name, billable_rate, color) VALUES ('Example Client A', 150, 'blue')`;
  await sql`INSERT INTO clients (name, billable_rate, color) VALUES ('Example Client B', 120, 'emerald')`;

  // Known firm apps -> Internal/Admin, non-billable, low-priority (evaluated
  // after any client-specific rules the user adds at priority < 100).
  const internalApps = ["ms-teams.exe", "Teams.exe", "OUTLOOK.EXE"];
  for (const app of internalApps) {
    await sql`
      INSERT INTO rules (match_app, client_id, project, billable, priority)
      VALUES (${app}, ${internalId}, 'Admin', false, 100)
    `;
  }
  // Outlook on the web + Teams web -> Internal/Admin.
  await sql`
    INSERT INTO rules (match_domain, client_id, project, billable, priority)
    VALUES ('outlook.office.com', ${internalId}, 'Admin', false, 100)
  `;
  await sql`
    INSERT INTO rules (match_domain, client_id, project, billable, priority)
    VALUES ('teams.microsoft.com', ${internalId}, 'Admin', false, 100)
  `;
  // Canva -> Internal by default (often client work; user can re-point it).
  await sql`
    INSERT INTO rules (match_domain, client_id, project, billable, priority)
    VALUES ('canva.com', ${internalId}, 'Design', false, 100)
  `;
}

/** Test helper: reset the shared connection (used by unit tests). */
export async function _resetConnectionForTests(): Promise<void> {
  if (_sql) {
    await _sql.end();
    _sql = null;
  }
  _ready = null;
}
