-- Tally schema for Supabase/Postgres. Applied once (Supabase SQL editor, or
-- `psql "$DATABASE_URL" -f lib/schema.sql`) against a fresh project. lib/db.ts
-- also runs this same set of `CREATE TABLE IF NOT EXISTS` statements on first
-- connect, so a brand-new Supabase database works with zero manual step —
-- this file exists mainly as a reviewable, explicit reference and for anyone
-- who prefers applying it by hand.

-- Team members whose machines push usage to this (shared) instance. Each
-- person's push agent authenticates with its unique token.
CREATE TABLE IF NOT EXISTS people (
  id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name   TEXT NOT NULL,
  token  TEXT NOT NULL UNIQUE,   -- bearer secret the machine's agent sends
  active BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS clients (
  id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                TEXT NOT NULL UNIQUE,
  billable_rate       DOUBLE PRECISION NOT NULL DEFAULT 0,
  color               TEXT,
  chrome_profile_dir  TEXT,  -- Chrome --profile-directory Tally provisioned
  chrome_profile_name TEXT   -- the profile's display name (matched in titles)
);

CREATE TABLE IF NOT EXISTS rules (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_app     TEXT,
  match_title   TEXT,
  match_domain  TEXT,
  match_profile TEXT,
  client_id     INTEGER REFERENCES clients(id) ON DELETE SET NULL,
  project       TEXT,
  billable      BOOLEAN NOT NULL DEFAULT true,
  priority      INTEGER NOT NULL DEFAULT 100
);

-- Per-day rollup of categorized usage, per person. person_id is the FIRST key
-- component so two teammates' otherwise-identical days never collide (the
-- whole reason a shared instance is possible). client_id uses -1 for "no
-- client" (kept from the SQLite schema so app code — which treats -1 as the
-- NO_CLIENT sentinel — doesn't need to change). 'unassigned' distinguishes "no
-- rule matched" from an explicit null-client rule. 'host' is part of the key
-- because the rollup groups by it (lib/ingest.ts).
CREATE TABLE IF NOT EXISTS daily_activity (
  person_id  INTEGER NOT NULL DEFAULT 1,
  day        TEXT NOT NULL,
  client_id  INTEGER NOT NULL,        -- -1 = no client
  app        TEXT NOT NULL,
  activity   TEXT NOT NULL,           -- cleaned window title (fine label)
  host       TEXT NOT NULL DEFAULT '',
  profile    TEXT NOT NULL DEFAULT '', -- Chrome profile name (client signal)
  billable   BOOLEAN NOT NULL DEFAULT false,
  unassigned BOOLEAN NOT NULL DEFAULT false,
  seconds    INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (person_id, day, client_id, app, activity, host, profile, billable, unassigned)
);

-- Raw pushed usage events, per person per day, kept as the central "source"
-- that replaces per-machine ActivityWatch: re-syncing rules or AI cleanup
-- recomputes the rollup from these instead of re-reading anyone's local AW.
CREATE TABLE IF NOT EXISTS pushed_events (
  person_id   INTEGER NOT NULL,
  day         TEXT NOT NULL,
  events_json JSONB NOT NULL,          -- JSON array of UsageEvent
  received_at TEXT NOT NULL,
  PRIMARY KEY (person_id, day)
);

-- Days whose rollup is complete (the day is over and was ingested).
CREATE TABLE IF NOT EXISTS day_finalized (
  day          TEXT PRIMARY KEY,
  finalized_at TEXT NOT NULL
);

-- LLM cleanup cache: each distinct raw host/title is enriched at most once
-- (per model), so views stay fast + deterministic and cost is bounded.
CREATE TABLE IF NOT EXISTS cleanup_cache (
  raw                   TEXT PRIMARY KEY,  -- the raw host (sites) or cleaned title
  kind                  TEXT NOT NULL,     -- 'site' | 'title'
  cleaned_label         TEXT NOT NULL,
  is_per_client         BOOLEAN NOT NULL DEFAULT false,
  suggested_domain      TEXT,
  suggested_client_name TEXT,              -- resolved to an id at read time
  confidence            DOUBLE PRECISION NOT NULL DEFAULT 0,
  model                 TEXT NOT NULL,     -- ENRICH_MODEL used (invalidates on model change)
  updated_at            TEXT NOT NULL
);

-- Simple key/value app settings (e.g. the shared Anthropic API key).
CREATE TABLE IF NOT EXISTS app_settings (
  key   TEXT PRIMARY KEY,
  value TEXT
);
